[server]
port = 17654
address = "0.0.0.0"
enableXsrfProtection = false
enableCORS = false

[theme]
base = "light"

[client]
showErrorDetails = false

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false

[logger]
level = "info"

[global]
showWarningOnDirectExecution = false
